install apg
install apple-gcc42
install brew-cask
install ctorrent
install direnv
install elasticsearch
install git
install go
install heroku-toolbelt
install iftop
install imagemagick
install ios-sim
install linode-cli
install macvim
install mariadb
install mercurial
install nginx
install node
install phantomjs
install postgresql
install pv
install pwgen
install rbenv
install rbenv-gem-rehash
tap thoughtbot/formulae
install rcm
install rsync
install ruby-build
install sqlite
install the_silver_searcher
install tig
install tmux
install tree
install vim
install watch
install wget
install wry
install zsh
